<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Agency - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
   

    <?php
echo "<body id=\"page-top\">\n";
echo "        <!-- Navigation-->\n";
echo "        <nav class=\"navbar navbar-expand-lg navbar-dark fixed-top\" id=\"mainNav\">\n";
echo "            <div class=\"container\">\n";
echo "                <a class=\"navbar-brand\" href=\"#page-top\"><i class=\"fa fa-fw fa-home\"></i><img src=\"assets/img/aeroplane.png\" alt=\"...\" /></a>\n";
echo "                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n";
echo "                    Menu\n";
echo "                    <i class=\"fas fa-bars ms-1\"></i>\n";
echo "                </button>\n";
echo "                <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\n";
echo "                    <ul class=\"navbar-nav text-uppercase ms-auto py-4 py-lg-0\">\n";
echo "                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#services\"><i class='fas fa-globe-asia'></i>Tour Packages</a></li>\n";
echo "                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#portfolio\"><i class='fas fa-plane'></i>Flights</a></li>\n";
echo "                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#about\"><i class=\"fa fa-user icon\"></i>Login/Register</a></li>\n";
echo "                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#team\"><i class='fas fa-money-check-alt'></i>Payment</a></li>\n";
echo "                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#contact\"><i class=\"fa fa-fw fa-envelope\"></i>Contact</a></li>\n";
echo "                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#aboutus\"><i class='fas fa-address-book'></i>About Us</a></li>\n";
echo "                    </ul>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </nav>\n";
echo "        <!-- Masthead-->\n";
echo "        <header class=\"masthead\">\n";
echo "            <div class=\"container\">\n";
echo "                <div class=\"masthead-subheading\">TIMOTHY'S TRAVEL AGENCY</div>\n";
echo "                <div class=\"masthead-heading text-uppercase\">One life.</div>\n";
echo "                <div class=\"masthead-heading text-uppercase\">One world.</div>\n";
echo "                <div class=\"masthead-heading text-uppercase\">Explore.</div>\n";
echo "                <a class=\"btn btn-primary btn-xl text-uppercase\" href=\"#services\">Tell Me More</a>\n";
echo "            </div>\n";
echo "        </header>\n";
echo "        <!-- Services-->\n";
echo "        <section class=\"page-section\" id=\"services\">\n";
echo "            <head>\n";
echo "                <title>Time</title>\n";
echo "                <script type=\"text/javascript\"> \n";
echo "                function display_c(){\n";
echo "                var refresh=1000; // Refresh rate in milli seconds\n";
echo "                mytime=setTimeout('display_ct()',refresh)\n";
echo "                }\n";
echo "                \n";
echo "                function display_ct() {\n";
echo "                var x = new Date()\n";
echo "                document.getElementById('ct').innerHTML = x;\n";
echo "                document.getElementById(\"ct\").style.fontFamily = \"	Courier New\";\n";
echo "                document.getElementById(\"ct\").style.fontWeight = \"800\";\n";
echo "                document.getElementById(\"ct\").style.outline = \"5px dotted #1DCD00\";\n";
echo "                document.getElementById(\"ct\").style.outlineOffset = \"10px\";\n";
echo "                document.getElementById(\"ct\").style.paddingLeft = \"13px\";\n";
echo "                document.getElementById(\"ct\").style.color = \"#343a4\";\n";
echo "                display_c();\n";
echo "                 }\n";
echo "                </script>\n";
echo "                </head>\n";
echo "                \n";
echo "                <body onload=display_ct();>\n";
echo "                <span id='ct' ></span>\n";
echo "                \n";
echo "                </body>\n";
echo "            <div class=\"container\">\n";
echo "                <div class=\"text-center\">\n";
echo "                    <h2 class=\"section-heading text-uppercase\"><i>Tour Packages</i></h2>\n";
echo "                    <h3 class=\"section-subheading text-muted\">\n";
echo "                        Discover the BEST packages for your family today and one of\n";
echo "                        the MOST affordable packages in Asia.</h3>\n";
echo "                    </div>\n";
echo "                \n";
echo "                <div class=\"row text-center\">\n";
echo "                    <h2 class=\"section-heading text-uppercase\" style=\"color:rgb(0, 0, 0);font-family:verdana;font-size:40px\"><u>THAILAND</u></h2>\n";
echo "                    \n";
echo "                    <div class=\"team\">\n";
echo "                        <img src=\"assets/img/team/bangkok.jpg\" alt=\"...\" width=\"1296\" height=\"500\">\n";
echo "                        <div class=\"text-block\">\n";
echo "                            <h4 style=\"font-family:verdana;\">Bangkok</h4>\n";
echo "                            <p>(5 DAYS, 4 NIGHTS) 4 PAX</p>\n";
echo "                          </div>\n";
echo "                        </span>\n";
echo "                        <p style=\"color:black;background-color:rgb(212, 212, 211);\"><b>Visit The Grand Palace and Temple Of Emerald Buddha.\n";
echo "                            The majority of Bangkok's significant tourist attractions are historical sites or religious monuments such as temples. Wat Phra Sri Rattanasamaram (Phra Kaew), Wat Phra Chetuphon Wimon Mangalaram (wat pho), Wat Arun Ratchawararam, Wat Sra Ket, and Phra Bor Banphot (Golden Mountain), Wat Ratchanadda, Wat Ratchanadda, Wat Ratchanadda, Wat Ratchanadda, Wat Ratchanadda and Wat Ratchan.\n";
echo "                            Ride a tuktuk to the Talad Rot Fai night market to enjoy the taste of Thai street food and cheap shopping.\n";
echo "                            Tickets of 4 to Siam Amazing Park for one whole day.\n";
echo "                            Shop around popular malls such as Siam Paragon and MBK.</b></p>\n";
echo "                            <p style=\"color:rgb(250, 250, 250);background-color:rgb(24, 109, 6);font-family:Copperplate;font-size:20px\"><b><i>FROM MYR 5100</i></b>\n";
echo "                            </p>\n";
echo "                    </div>\n";
echo "                    \n";
echo "                    <div class=\"row text-center\">\n";
echo "                        <div class=\"team\">\n";
echo "                            <img src=\"assets/img/team/krabi.jpg\" alt=\"...\" width=\"1272\" height=\"500\">\n";
echo "                            <div class=\"text-block\">\n";
echo "                                <h4 style=\"font-family:verdana;\">Krabi</h4>\n";
echo "                                <p>(3 DAYS, 2 NIGHTS) 2 PAX</p>\n";
echo "                            </div>\n";
echo "                        </span>\n";
echo "                        <p style=\"color:black;background-color:rgb(212, 212, 211)\"><b>Snorkelling and island hopping to 5 different islands on boat (Equipment is provided).\n";
echo "                                Kayaking for 2 people.Krabi is a seaside province on Thailand's southern coast, bordering the Andaman Sea. It is regarded as a type of heaven, with stunning beaches and limestone structures. With over 150 offshore islands and a plethora of leisure activities, it's no surprise that many travellers consider Krabi to be the quintessential beach holiday location.\n";
echo "                                See outstanding beauty at Thung Teao Forest Natural Park.\n";
echo "                                Visit a temple in a cave at Wat Tham Sua.</b></p>\n";
echo "                                <p style=\"color:rgb(251, 255, 251);background-color:rgb(24, 109, 6);font-family:Copperplate;font-size:20px\"><b><i>FROM MYR 1800</i></b>\n";
echo "                                </p>\n";
echo "                        </div>\n";
echo "                        <div class=\"row text-center\">\n";
echo "                            <h2 class=\"section-heading text-uppercase\" style=\"color:rgb(0, 0, 0);font-family:verdana;font-size:40px\"><u>JAPAN</u></h2>\n";
echo "        \n";
echo "                            <div class=\"team\">\n";
echo "                                <img src=\"assets/img/team/tokyo.jpg\" alt=\"...\" width=\"1248\" height=\"500\">\n";
echo "                                <div class=\"text-block\">\n";
echo "                                    <h4 style=\"font-family:verdana;\">Tokyo</h4>\n";
echo "                                    <p>(7 DAYS, 6 NIGHTS) 4 PAX</p>\n";
echo "                                </div>\n";
echo "                            </span>\n";
echo "                                <p style=\"color:black;background-color:rgb(212, 212, 211)\"><b>Tokyo tourists have an almost limitless selection of shopping, entertainment, cultural, and food options. The city's history can be found in neighbourhoods like Asakusa, as well as other superb museums, old temples, and parks. Contrary to popular belief, Tokyo has a lot of lovely green spots both in the city centre and on the outskirts, all of which are accessible by rail.\n";
echo "                                    4 STAR Hotel located 1 station away from city centre by train.\n";
echo "                                    Shop till you drop at Ginza District.\n";
echo "                                    Visit Tokyo Sky Tree, the tallest structure in Japan.\n";
echo "                                    1 week train pass provided to help you travel easily.\n";
echo "                                    Visit Ueno Park and Zoo where the cherry blossoms blond during spring and get nice pictures.</b></p>\n";
echo "                                    <p style=\"color:rgb(253, 253, 253);background-color:rgb(24, 109, 6);font-family:Copperplate;font-size:20px\"><b><i>FROM MYR 8000</i></b>\n";
echo "                                    </p>\n";
echo "                            </div>\n";
echo "                            <div class=\"row text-center\">\n";
echo "                                <div class=\"team\">\n";
echo "                                    <img src=\"assets/img/team/osaka.jpg\" alt=\"...\" width=\"1224\" height=\"500\">\n";
echo "                                    <div class=\"text-block\">\n";
echo "                                        <h4 style=\"font-family:verdana;\">Osaka</h4>\n";
echo "                                        <p>(6 DAYS, 5 NIGHTS) 6 PAX</p>\n";
echo "                                    </div>\n";
echo "                                </span>\n";
echo "                                    <p style=\"color:black;background-color:rgb(212, 212, 211)\"><b>Step off the bullet train into an area brimming with lively nightlife, delectable cuisine, and straightforward, welcoming residents. Osaka boasts a historical aspect as well as abundance of shopping and modern attractions, the centrepiece of which is Osaka Castle. The castle is a fantastic spot to learn about Japanese history and roam around the lovely gardens, especially during cherry blossom season in April.\n";
echo "                                        Snorkelling and island hopping to 5 different islands on boat (Equipment is provided).\n";
echo "                                        Kayaking for 2 people.\n";
echo "                                        See outstanding beauty at Thung Teao Forest Natural Park.\n";
echo "                                        Visit a temple in a cave at Wat Tham SuaHomestay spacious enough for 6 people.\n";
echo "                                        Visit Osaka Castle and Osaka Aquarium Kaiyukan.\n";
echo "                                        Have fun in Universal Studio Japan.\n";
echo "                                        Free SIM cards with 5GB of data.\n";
echo "                                        Taste the awesome takoyaki which is a well-known fast food in Osaka.</b></p>\n";
echo "                                        <p style=\"color:rgb(254, 255, 254);background-color:rgb(24, 109, 6);font-family:Copperplate;font-size:20px\"><b><i>FROM MYR 9200</i></b>\n";
echo "                                        </p>\n";
echo "                                        <div class=\"row text-center\">\n";
echo "                                            <h2 class=\"section-heading text-uppercase\" style=\"color:rgb(0, 0, 0);font-family:verdana;font-size:40px\"><u>COMBODIA</u></h2>                        \n";
echo "                                            <div class=\"row text-center\">\n";
echo "                                                <div class=\"team\">\n";
echo "                                                    <img src=\"assets/img/team/ksr.jpg\" alt=\"...\" width=\"1200\" height=\"500\">\n";
echo "                                                <div class=\"text-block\">\n";
echo "                                                    <h4 style=\"font-family:verdana;\">Krong Siem Reap</h4>\n";
echo "                                                    <p>(4 DAYS, 3 NIGHTS) 2 PAX</p>\n";
echo "                                                </div>\n";
echo "                                            </span>\n";
echo "                                                <p style=\"color:black;background-color:rgb(212, 212, 211)\"><b>Visit Angkor Wat, one of the world's most incredible ancient sites.\n";
echo "                                                    Dine in at cosy cafes with beautiful decorations and wonderful coffee.\n";
echo "                                                    Eat at The Sugarpalm Restaurant where they serve great Khmer cuisine.\n";
echo "                                                    The sun shines virtually all year in Cambodia. The average temperature is roughly 27 degrees Celsius, with a low of 16 degrees. The coldest months of the year are December and January. Climate-related facts in general: The rainy season is from May through October (27-35c, with humidity up to 90 percent .)\n";
echo "                                                    November through March is the cool season (17-27c).\n";
echo "                                                    The hot season is from March through May. (28c -36c).</b></p>\n";
echo "                                                    <p style=\"color:rgb(248, 250, 248);background-color:rgb(24, 109, 6);font-family:Copperplate;font-size:20px\"><b><i>FROM MYR 3000</i></b> \n";
echo "                                                    </p>\n";
echo "                                                    \n";
echo "                                </div>\n";
echo "                                <div class=\"row text-center\">\n";
echo "                                    <h2 class=\"section-heading text-uppercase\" style=\"color:rgb(0, 0, 0);font-family:verdana;font-size:40px\"><u>VIETNAM</u></h2>                \n";
echo "                                    <div class=\"row text-center\">\n";
echo "                                        <div class=\"team\">\n";
echo "                                            <img src=\"assets/img/team/hch.jpg\" alt=\"...\" width=\"1153\" height=\"500\">\n";
echo "                                        <div class=\"text-block\">\n";
echo "                                            <h4 style=\"font-family:verdana;\">Ho Chi Minh</h4>\n";
echo "                                            <p>(4 DAYS, 3 NIGHTS) 2 PAX</p>\n";
echo "                                        </div>\n";
echo "                                    </span>\n";
echo "                                        <p style=\"color:black;background-color:rgb(212, 212, 211)\"><b>With well-preserved colonial architecture and battle artefacts from the tragic Vietnam War, as well as modern skyscrapers, stylish sports clubs, and enormous retail malls set against a cityscape background, Ho Chi Minh City attractions are a colourful blend of old and new. No two areas in Ho Chi Minh City are the identical, and there are plenty of magnificent pagodas and Bui Vien temples to see.\n";
echo "                                            Visit Chao Dai Temple, one of the most popular temples over there.\n";
echo "                                            Crawl through the 250km plus network of tunnels,Cu Chi Tunnels.\n";
echo "                                            Take a tour at Ho Chi Minh City Museum, that waas once home to the Cochichina's governor.</b></p>\n";
echo "                                            <p style=\"color:rgb(255, 255, 255);background-color:rgb(24, 109, 6);font-family:Copperplate;font-size:20px\"><b><i>FROM MYR 3600<i></i></b> \n";
echo "                                            </p>\n";
echo "                        </span>\n";
echo "                        \n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </section>\n";
echo "        <!-- Portfolio Grid-->\n";
echo "        <section class=\"page-section bg-light\" id=\"portfolio\">\n";
echo "            <div class=\"container\">\n";
echo "                <div class=\"text-center\">\n";
echo "                    <h2 class=\"section-heading text-uppercase\">Flights</h2>\n";
echo "                    <h3 class=\"section-subheading text-muted\">Class and Meal Packages.</h3>\n";
echo "                </div>\n";
echo "                <div class=\"row\">\n";
echo "                    <div class=\"col-lg-4 col-sm-6 mb-4\">\n";
echo "                        <!-- Portfolio item 1-->\n";
echo "                        <div class=\"portfolio-item\">\n";
echo "                            <a class=\"portfolio-link\" data-bs-toggle=\"modal\" href=\"#portfolioModal1\">\n";
echo "                                <div class=\"portfolio-hover\">\n";
echo "                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\n";
echo "                                </div>\n";
echo "                                <img class=\"img-fluid\" src=\"assets/img/portfolio/1.jpg\" alt=\"...\" />\n";
echo "                            </a>\n";
echo "                            <div class=\"portfolio-caption\">\n";
echo "                                <div class=\"portfolio-caption-heading\">First Class</div>\n";
echo "                                <div class=\"portfolio-caption-subheading text-muted\">Class + Meals</div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-lg-4 col-sm-6 mb-4\">\n";
echo "                        <!-- Portfolio item 2-->\n";
echo "                        <div class=\"portfolio-item\">\n";
echo "                            <a class=\"portfolio-link\" data-bs-toggle=\"modal\" href=\"#portfolioModal2\">\n";
echo "                                <div class=\"portfolio-hover\">\n";
echo "                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\n";
echo "                                </div>\n";
echo "                                <img class=\"img-fluid\" src=\"assets/img/portfolio/2.jpg\" alt=\"...\" />\n";
echo "                            </a>\n";
echo "                            <div class=\"portfolio-caption\">\n";
echo "                                <div class=\"portfolio-caption-heading\">Business Class</div>\n";
echo "                                <div class=\"portfolio-caption-subheading text-muted\">Class + Meals</div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-lg-4 col-sm-6 mb-4\">\n";
echo "                        <!-- Portfolio item 3-->\n";
echo "                        <div class=\"portfolio-item\">\n";
echo "                            <a class=\"portfolio-link\" data-bs-toggle=\"modal\" href=\"#portfolioModal3\">\n";
echo "                                <div class=\"portfolio-hover\">\n";
echo "                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\n";
echo "                                </div>\n";
echo "                                <img class=\"img-fluid\" src=\"assets/img/portfolio/3.jpg\" alt=\"...\" />\n";
echo "                            </a>\n";
echo "                            <div class=\"portfolio-caption\">\n";
echo "                                <div class=\"portfolio-caption-heading\">Premium Economy Class</div>\n";
echo "                                <div class=\"portfolio-caption-subheading text-muted\">Class + Meals</div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-lg-4 col-sm-6 mb-4 mb-lg-0\">\n";
echo "                        <!-- Portfolio item 4-->\n";
echo "                        <div class=\"portfolio-item\">\n";
echo "                            <a class=\"portfolio-link\" data-bs-toggle=\"modal\" href=\"#portfolioModal4\">\n";
echo "                                <div class=\"portfolio-hover\">\n";
echo "                                    <div class=\"portfolio-hover-content\"><i class=\"fas fa-plus fa-3x\"></i></div>\n";
echo "                                </div>\n";
echo "                                <img class=\"img-fluid\" src=\"assets/img/portfolio/4.jpg\" alt=\"...\" />\n";
echo "                            </a>\n";
echo "                            <div class=\"portfolio-caption\">\n";
echo "                                <div class=\"portfolio-caption-heading\">Economy Class</div>\n";
echo "                                <div class=\"portfolio-caption-subheading text-muted\">Class + Meals</div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    \n";
echo "                       \n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </section>\n";
echo "        <!-- About-->\n";
echo "        <section class=\"page-section\" id=\"about\">\n";
echo "            <div class=\"container\">\n";
echo "            <div class=\"text-center\">\n";
echo "            <h2>Modal Login Form</h2>  \n";
echo "             </div>            \n";
echo "              <form class=\"modal-content animate\" action=\"/action_page.php\" method=\"post\">\n";
echo "                <div class=\"imgcontainer\">\n";
echo "  \n";
echo "                  <div class=\"center\"><img class=\"mx-auto rounded-circle\" src=\"assets/img/avatar.jpg\" alt=\"...\" width=\"200\" height=\"200\"/>\n";
echo "                </div>\n";
echo "            \n";
echo "                <div class=\"container\">\n";
echo "                  <label for=\"uname\"><b>Username</b></label>\n";
echo "                  <input type=\"text\" placeholder=\"Enter Username\" name=\"uname\" required>\n";
echo "            \n";
echo "                  <label for=\"psw\"><b>Password</b></label>\n";
echo "                  <input type=\"password\" placeholder=\"Enter Password\" name=\"psw\" required>\n";
echo "                    \n";
echo "                  <button type=\"submit\">Login</button>\n";
echo "                  <label>\n";
echo "                    <input type=\"checkbox\" checked=\"checked\" name=\"remember\"> Remember me\n";
echo "                  </label>\n";
echo "                </div>\n";
echo "              </form>\n";

            
              $host='localhost';
$user='root';
$password='';
$dbname='phpmyadmin';

$conn=mysqli_connect($host,$user,$password,$dbname);

if(isset($_POST['submit'])){
    if(!empty($_POST['uname']) && !empty($_POST['psw']))){
        $uname = $_POST['uname'];
        $psw = $_POST['psw'];

        $query = "insert into form(uname and psw) values('$uname','$psw')";

        $run = mysqli_query($conn,$query) or die(mysqli_error());

        if ($run){
            echo "Form submitted successfully";
        }
        else {
            echo "Form not submitted";
        }

    }
    else{
        echo "all fields required";
    }
}

echo "</div>\n";
echo "            \n";
echo "            <script>\n";
echo "            // Get the modal\n";
echo "            var modal = document.getElementById('id01');\n";
echo "            \n";
echo "            // When the user clicks anywhere outside of the modal, close it\n";
echo "            window.onclick = function(event) {\n";
echo "                if (event.target == modal) {\n";
echo "                    modal.style.display = \"none\";\n";
echo "                }\n";
echo "            }\n";
echo "            </script>\n";
echo "        </section>\n";
echo "        <form action=\"action_page.php\">\n";
echo "            <div class=\"container\">\n";
echo "            <div class=\"text-center\">\n";
echo "              <h1>Register</h1>\n";
echo "              <p>Please fill in this form to create an account.</p>\n";
echo "              <hr>\n";
echo "            </div>\n";
echo "              <label for=\"email\"><b>Email</b></label>\n";
echo "              <input type=\"text\" placeholder=\"Enter Email\" name=\"email\" id=\"email\" required>\n";
echo "          \n";
echo "              <label for=\"psw\"><b>Password</b></label>\n";
echo "              <input type=\"password\" placeholder=\"Enter Password\" name=\"psw\" id=\"psw\" required>\n";
echo "          \n";
echo "              <label for=\"psw-repeat\"><b>Repeat Password</b></label>\n";
echo "              <input type=\"password\" placeholder=\"Repeat Password\" name=\"psw-repeat\" id=\"psw-repeat\" required>\n";
echo "              <hr>\n";
echo "          \n";
echo "              <p>By creating an account you agree to our <a href=\"#\">Terms & Privacy</a>.</p>\n";
echo "              <button type=\"submit\" class=\"registerbtn\">Register</button>\n";
echo "            </div>\n";
echo "          </form>\n";

          
              $host='localhost';
              $user='root';
$password='';
$dbname='phpmyadmin';

$conn=mysqli_connect($host,$user,$password,$dbname);

if(isset($_POST['submit'])){
    if(!empty($_POST['email']) && !empty($_POST['psw']) && !empty($_POST['psw-repeat']))){
        $email = $_POST['email'];
        $psw = $_POST['psw'];
        $psw = $_POST['psw-repeat'];

        $query = "insert into form(uname and psw) values('$uname','$psw','$psw-repeat')";

        $run = mysqli_query($conn,$query) or die(mysqli_error());

        if ($run){
            echo "Form submitted successfully";
        }
        else {
            echo "Form not submitted";
        }

    }
    else{
        echo "all fields required";
    }
}

echo "<!-- Team-->\n";
echo "        <section class=\"page-section bg-light\" id=\"team\">\n";
echo "           \n";
echo "            <h2 style=\"text-align:center\">Responsive Checkout Form</h2>\n";
echo "            <p style=\"text-align:center\">Accept online payments on any device or channel, whatever your business model. You’ll be up and running quickly, can add payment methods easily, and increase your conversion rates.</p>\n";
echo "            <div class=\"row\">\n";
echo "              <div class=\"col-75\">\n";
echo "                <div class=\"container\">\n";
echo "                  <form action=\"/action_page.php\">\n";
echo "                  \n";
echo "                    <div class=\"row\">\n";
echo "                      <div class=\"col-50\">\n";
echo "                        <h3>Billing Address</h3>\n";
echo "                        <label for=\"fname\"><i class=\"fa fa-user\"></i> Full Name</label>\n";
echo "                        <input type=\"text\" id=\"fname\" name=\"firstname\" placeholder=\"John M. Doe\">\n";
echo "                        <label for=\"email\"><i class=\"fa fa-envelope\"></i> Email</label>\n";
echo "                        <input type=\"text\" id=\"email\" name=\"email\" placeholder=\"john@example.com\">\n";
echo "                        <label for=\"adr\"><i class=\"fa fa-address-card-o\"></i> Address</label>\n";
echo "                        <input type=\"text\" id=\"adr\" name=\"address\" placeholder=\"542 W. 15th Street\">\n";
echo "                        <label for=\"city\"><i class=\"fa fa-institution\"></i> City</label>\n";
echo "                        <input type=\"text\" id=\"city\" name=\"city\" placeholder=\"New York\">\n";
echo "            \n";
echo "                        <div class=\"row\">\n";
echo "                          <div class=\"col-50\">\n";
echo "                            <label for=\"state\">State</label>\n";
echo "                            <input type=\"text\" id=\"state\" name=\"state\" placeholder=\"NY\">\n";
echo "                          </div>\n";
echo "                          <div class=\"col-50\">\n";
echo "                            <label for=\"zip\">Zip</label>\n";
echo "                            <input type=\"text\" id=\"zip\" name=\"zip\" placeholder=\"10001\">\n";
echo "                          </div>\n";
echo "                        </div>\n";
echo "                      </div>\n";
echo "            \n";
echo "                      <div class=\"col-50\">\n";
echo "                        <h3>Payment</h3>\n";
echo "                        <label for=\"fname\">Accepted Cards</label>\n";
echo "                        <div class=\"icon-container\">\n";
echo "                            <img src=\"assets/img/card.jpg\"  width=\"200\" height=\"150\" alt=\"Card Types\">\n";
echo "                        </div>\n";
echo "                        <br>\n";
echo "                        <label for=\"cname\">Name on Card</label>\n";
echo "                        <input type=\"text\" id=\"cname\" name=\"cardname\" placeholder=\"John More Doe\">\n";
echo "                        <label for=\"ccnum\">Credit card number</label>\n";
echo "                        <input type=\"text\" id=\"ccnum\" name=\"cardnumber\" placeholder=\"1111-2222-3333-4444\">\n";
echo "                        <label for=\"expmonth\">Exp Month</label>\n";
echo "                        <input type=\"text\" id=\"expmonth\" name=\"expmonth\" placeholder=\"September\">\n";
echo "                        <div class=\"row\">\n";
echo "                          <div class=\"col-50\">\n";
echo "                            <label for=\"expyear\">Exp Year</label>\n";
echo "                            <input type=\"text\" id=\"expyear\" name=\"expyear\" placeholder=\"2018\">\n";
echo "                          </div>\n";
echo "                          <div class=\"col-50\">\n";
echo "                            <label for=\"cvv\">CVV</label>\n";
echo "                            <input type=\"text\" id=\"cvv\" name=\"cvv\" placeholder=\"352\">\n";
echo "                          </div>\n";
echo "                        </div>\n";
echo "                      </div>\n";
echo "                      \n";
echo "                    </div>\n";
echo "                    <label>\n";
echo "                      <input type=\"checkbox\" checked=\"checked\" name=\"sameadr\"> Shipping address same as billing\n";
echo "                    </label>\n";
echo "                    <input type=\"submit\" value=\"Continue to checkout\" class=\"btn\">\n";
echo "                  </form>\n";
echo "                </div>\n";
echo "              </div>\n";
echo "              <div class=\"col-25\">\n";
echo "                <div class=\"container\">\n";
echo "                  <h4>Destination Package<span class=\"price\" style=\"color:black\"></span></h4>\n";
echo "                  <p>Choose your package : </p>\n";
echo "                    <p><b>THAILAND</b></p>\n";
echo "                    <input name=\"pkg\" type=\"radio\" value=\"\"/><i>Bangkok (5 DAYS, 4 NIGHTS) 4 PAX</i>\n";
echo "                    <br/>\n";
echo "                    <input name=\"pkg\" type=\"radio\" value=\"\"/><i>Krabi (3 DAYS, 2 NIGHTS) 2 PAX</i>\n";
echo "                    \n";
echo "                    <br/>\n";
echo "                    <br/>\n";
echo "\n";
echo "                    <p><b>JAPAN</b></p>\n";
echo "                    <input name=\"pkg\" type=\"radio\" value=\"\"/><i>Tokyo (7 DAYS, 6 NIGHTS) 4 PAX</i>\n";
echo "                    <br/>\n";
echo "                    <input name=\"pkg\" type=\"radio\" value=\"\"/><i>Osaka (6 DAYS, 5 NIGHTS) 6 PAX</i>\n";
echo "\n";
echo "                    <br/>\n";
echo "                    <br/>\n";
echo "\n";
echo "                    <p><b>COMBODIA</b></p>\n";
echo "                    <input name=\"pkg\" type=\"radio\" value=\"\"/><i>Krong Siem Reap (4 DAYS, 3 NIGHTS) 2 PAX</i>\n";
echo "                    \n";
echo "                    <br/>\n";
echo "                    <br/>\n";
echo "\n";
echo "                    <p><b>VIETNAM</b></p>\n";
echo "                    <input name=\"pkg\" type=\"radio\" value=\"\"/><i>Ho Chi Minh (4 DAYS, 3 NIGHTS) 2 PAX</i>\n";
echo "\n";
echo "                  <hr>\n";
echo "                 \n";
echo "                  <p>Choose your Flight Class:</p>\n";
echo "                  <input type=\"radio\" name=\"class\" value=\"\"/><i>First Class</i>\n";
echo "                  <br>\n";
echo "                  <input type=\"radio\" name=\"class\" value=\"\"/><i>Business Class</i>\n";
echo "                  <br>\n";
echo "                  <input type=\"radio\" name=\"class\" value=\"\"/><i>Premium Economy Class</i>\n";
echo "                  <br>\n";
echo "                  <input type=\"radio\" name=\"class\" value=\"\"/><i>Economy Class</i>\n";
echo "\n";
echo "                  <hr>\n";
echo "\n";
echo "                </div>\n";
echo "              </div>\n";
echo "            </div>\n";
echo "                \n";
echo "\n";
echo "        </section>\n";
echo "        <!-- Clients-->\n";
echo "        <div class=\"py-5\">\n";
echo "            <div class=\"container\">\n";
echo "                <div class=\"row align-items-center\">\n";
echo "                    <div class=\"col-md-3 col-sm-6 my-3\">\n";
echo "                        <a href=\"#!\"><img class=\"img-fluid img-brand d-block mx-auto\" src=\"assets/img/logos/microsoft.svg\" alt=\"...\" /></a>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-md-3 col-sm-6 my-3\">\n";
echo "                        <a href=\"#!\"><img class=\"img-fluid img-brand d-block mx-auto\" src=\"assets/img/logos/google.svg\" alt=\"...\" /></a>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-md-3 col-sm-6 my-3\">\n";
echo "                        <a href=\"#!\"><img class=\"img-fluid img-brand d-block mx-auto\" src=\"assets/img/logos/facebook.svg\" alt=\"...\" /></a>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-md-3 col-sm-6 my-3\">\n";
echo "                        <a href=\"#!\"><img class=\"img-fluid img-brand d-block mx-auto\" src=\"assets/img/logos/ibm.svg\" alt=\"...\" /></a>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "        <!-- Contact-->\n";
echo "        <section class=\"page-section\" id=\"contact\">\n";
echo "            <div class=\"container\">\n";
echo "                <div class=\"text-center\">\n";
echo "                    <h2 class=\"section-heading text-uppercase\">CONTACT US</h2>\n";
echo "                    <h3 class=\"section-subheading text-muted\">This page is used to identify the problems that occur when customers are using our website and we use it to improve the quality of our website.</h3>\n";
echo "                </div>\n";
echo "                <!-- * * * * * * * * * * * * * * *-->\n";
echo "                <!-- * * SB Forms Contact Form * *-->\n";
echo "                <!-- * * * * * * * * * * * * * * *-->\n";
echo "                <!-- This form is pre-integrated with SB Forms.-->\n";
echo "                <!-- To make this form functional, sign up at-->\n";
echo "                <!-- https://startbootstrap.com/solution/contact-forms-->\n";
echo "                <!-- to get an API token!-->\n";
echo "                <form id=\"contactForm\" data-sb-form-api-token=\"API_TOKEN\">\n";
echo "                    <div class=\"row align-items-stretch mb-5\">\n";
echo "                        <div class=\"col-md-6\">\n";
echo "                            <div class=\"form-group\">\n";
echo "                                <!-- Name input-->\n";
echo "                                <input class=\"form-control\" id=\"name\" type=\"text\" placeholder=\"Your Name *\" data-sb-validations=\"required\" />\n";
echo "                                <div class=\"invalid-feedback\" data-sb-feedback=\"name:required\">A name is required.</div>\n";
echo "                            </div>\n";
echo "                            <div class=\"form-group\">\n";
echo "                                <!-- Email address input-->\n";
echo "                                <input class=\"form-control\" id=\"email\" type=\"email\" placeholder=\"Your Email *\" data-sb-validations=\"required,email\" />\n";
echo "                                <div class=\"invalid-feedback\" data-sb-feedback=\"email:required\">An email is required.</div>\n";
echo "                                <div class=\"invalid-feedback\" data-sb-feedback=\"email:email\">Email is not valid.</div>\n";
echo "                            </div>\n";
echo "                            <div class=\"form-group mb-md-0\">\n";
echo "                                <!-- Phone number input-->\n";
echo "                                <input class=\"form-control\" id=\"phone\" type=\"tel\" placeholder=\"Your Phone *\" data-sb-validations=\"required\" />\n";
echo "                                <div class=\"invalid-feedback\" data-sb-feedback=\"phone:required\">A phone number is required.</div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                        <div class=\"col-md-6\">\n";
echo "                            <div class=\"form-group form-group-textarea mb-md-0\">\n";
echo "                                <!-- Message input-->\n";
echo "                                <textarea class=\"form-control\" id=\"message\" placeholder=\"Your Message *\" data-sb-validations=\"required\"></textarea>\n";
echo "                                <div class=\"invalid-feedback\" data-sb-feedback=\"message:required\">A message is required.</div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <!-- Submit success message-->\n";
echo "                    <!---->\n";
echo "                    <!-- This is what your users will see when the form-->\n";
echo "                    <!-- has successfully submitted-->\n";
echo "                    <div class=\"d-none\" id=\"submitSuccessMessage\">\n";
echo "                        <div class=\"text-center text-white mb-3\">\n";
echo "                            <div class=\"fw-bolder\">Form submission successful!</div>\n";
echo "                            To activate this form, sign up at\n";
echo "                            <br />\n";
echo "                            <a href=\"https://startbootstrap.com/solution/contact-forms\">https://startbootstrap.com/solution/contact-forms</a>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <!-- Submit error message-->\n";
echo "                    <!---->\n";
echo "                    <!-- This is what your users will see when there is-->\n";
echo "                    <!-- an error submitting the form-->\n";
echo "                    <div class=\"d-none\" id=\"submitErrorMessage\"><div class=\"text-center text-danger mb-3\">Error sending message!</div></div>\n";
echo "                    <!-- Submit Button-->\n";
echo "                    <div class=\"text-center\"><button class=\"btn btn-primary btn-xl text-uppercase disabled\" id=\"submitButton\" type=\"submit\">Send Message</button></div>\n";
echo "                </form>\n";
echo "            </div>\n";
echo "            </section>\n";
echo "            \n";
echo "            <section class=\"page-section\" id=\"aboutus\">\n";
echo "                <div class=\"container\">\n";
echo "                    <div class=\"text-center\">\n";
echo "                        <h2 class=\"section-heading text-uppercase\">Our Amazing Team</h2>\n";
echo "                        <h3 class=\"section-subheading text-muted\">Great things are rarely achieved by just one person. Usually, they are accomplished by a group of people, and when everyone is committed to the overall goal, teams move faster, are more innovative and more successful. Successful teamwork is essential for anyone attempting complete projects successfully.</h3>\n";
echo "                    </div>\n";
echo "                    <div class=\"row\">\n";
echo "                        <div class=\"col-lg-4\">\n";
echo "                            <div class=\"team-member\">\n";
echo "                                <img class=\"mx-auto rounded-circle\" src=\"assets/img/team/1.jpg\" alt=\"...\" />\n";
echo "                                <h4>Rajveer Singh</h4>\n";
echo "                                <p class=\"text-muted\">Lead Designer</p>\n";
echo "                                <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-twitter\"></i></a>\n";
echo "                                <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-facebook-f\"></i></a>\n";
echo "                                <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-linkedin-in\"></i></a>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                        <div class=\"col-lg-4\">\n";
echo "                            <div class=\"team-member\">\n";
echo "                                <img class=\"mx-auto rounded-circle\" src=\"assets/img/team/2.jpg\" alt=\"...\" />\n";
echo "                                <h4>Diana Petersen</h4>\n";
echo "                                <p class=\"text-muted\">Lead Marketer</p>\n";
echo "                                <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-twitter\"></i></a>\n";
echo "                                <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-facebook-f\"></i></a>\n";
echo "                                <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-linkedin-in\"></i></a>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                        <div class=\"col-lg-4\">\n";
echo "                            <div class=\"team-member\">\n";
echo "                                <img class=\"mx-auto rounded-circle\" src=\"assets/img/team/3.jpg\" alt=\"...\" />\n";
echo "                                <h4>Rakesh Ramesh</h4>\n";
echo "                                <p class=\"text-muted\">Lead Developer</p>\n";
echo "                                <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-twitter\"></i></a>\n";
echo "                                <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-facebook-f\"></i></a>\n";
echo "                                <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-linkedin-in\"></i></a>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <div class=\"row\">\n";
echo "                        <div class=\"col-lg-8 mx-auto text-center\"><p class=\"large text-muted\">“Individual commitment to a group effort—that is what makes a team work, a company work, a society work, a civilisation work.”\n";
echo "\n";
echo "                            Vince Lombardi</p></div>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "\n";
echo "            </section>\n";
echo "        </section>\n";
echo "        <!-- Footer-->\n";
echo "        <footer class=\"footer py-4\">\n";
echo "            <div class=\"container\">\n";
echo "                <div class=\"row align-items-center\">\n";
echo "                    <div class=\"col-lg-4 text-lg-start\">Copyright &copy; Your Website 2021</div>\n";
echo "                    <div class=\"col-lg-4 my-3 my-lg-0\">\n";
echo "                        <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-twitter\"></i></a>\n";
echo "                        <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-facebook-f\"></i></a>\n";
echo "                        <a class=\"btn btn-dark btn-social mx-2\" href=\"#!\"><i class=\"fab fa-linkedin-in\"></i></a>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-lg-4 text-lg-end\">\n";
echo "                        <a class=\"link-dark text-decoration-none me-3\" href=\"#!\">Privacy Policy</a>\n";
echo "                        <a class=\"link-dark text-decoration-none\" href=\"#!\">Terms of Use</a>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </footer>\n";
echo "        <!-- Portfolio Modals-->\n";
echo "        <!-- Portfolio item 1 modal popup-->\n";
echo "        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal1\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n";
echo "            <div class=\"modal-dialog\">\n";
echo "                <div class=\"modal-content\">\n";
echo "                    <div class=\"close-modal\" data-bs-dismiss=\"modal\"><img src=\"assets/img/close-icon.svg\" alt=\"Close modal\" /></div>\n";
echo "                    <div class=\"container\">\n";
echo "                        <div class=\"row justify-content-center\">\n";
echo "                            <div class=\"col-lg-8\">\n";
echo "                                <div class=\"modal-body\">\n";
echo "                                    <!-- Project details-->\n";
echo "                                    <h2 class=\"text-uppercase\">First Class</h2>\n";
echo "                                    <p class=\"item-intro text-muted\">First Class, generally the most expensive and most comfortable accommodations available.</p>\n";
echo "                                    <img class=\"img-fluid d-block mx-auto\" src=\"assets/img/portfolio/1.jpg\" alt=\"...\" />\n";
echo "                                    <p>• Flying in comfort is now yours to enjoy with the Premium Flatbed. This spacious seat reclines to become a full flatbed when desired. It also features a privacy screen, an adjustable head and foot rest, as well as a pillow and duvet for maximum comfort. In addition, it also comes with a reading light and universal power port.\n";
echo "                                    <img class=\"img-fluid d-block mx-auto\" src=\"assets/img/portfolio/meals.jpg\" alt=\"...\" />\n";
echo "\n";
echo "                                    <p>• Named after the much-loved coconut milk, our Santan menu offers a wide selection of Asean, international and vegetarian options for everyone. Our Santan Combo Meal provides guests with great value and savings, plus the ability to choose and secure your favourite Hot Meal from a wide selection.\n";
echo "                                    </p>\n";
echo "                                    <ul class=\"list-inline\">\n";
echo "                                        <li>\n";
echo "                                            <strong>Client:</strong>\n";
echo "                                            First Class\n";
echo "                                        </li>\n";
echo "                                        <li>\n";
echo "                                            <strong>Category:</strong>\n";
echo "                                            Class and Meals\n";
echo "                                        </li>\n";
echo "                                        <li>\n";
echo "                                            <strong>Price</strong>\n";
echo "                                            MYR 1200 (Per Pax)\n";
echo "                                        </li>\n";
echo "                                    </ul>\n";
echo "                                    <button class=\"btn btn-primary btn-xl text-uppercase\" data-bs-dismiss=\"modal\" type=\"button\">\n";
echo "                                        <i class=\"fas fa-times me-1\"></i>\n";
echo "                                        BACK TO FLIGHT PACKAGES\n";
echo "                                    </button>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "        <!-- Portfolio item 2 modal popup-->\n";
echo "        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal2\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n";
echo "            <div class=\"modal-dialog\">\n";
echo "                <div class=\"modal-content\">\n";
echo "                    <div class=\"close-modal\" data-bs-dismiss=\"modal\"><img src=\"assets/img/close-icon.svg\" alt=\"Close modal\" /></div>\n";
echo "                    <div class=\"container\">\n";
echo "                        <div class=\"row justify-content-center\">\n";
echo "                            <div class=\"col-lg-8\">\n";
echo "                                <div class=\"modal-body\">\n";
echo "                                    <!-- Project details-->\n";
echo "                                    <h2 class=\"text-uppercase\">Business</h2>\n";
echo "                                    <p class=\"item-intro text-muted\">• Business Class, high quality, traditionally purchased by business travelers (sometimes called executive class).</p>\n";
echo "                                    <img class=\"img-fluid d-block mx-auto\" src=\"assets/img/portfolio/2.jpg\" alt=\"...\" />\n";
echo "                                    <p>Comfort is taken to a whole new level with our top notch amenities and award-winning service.*Flat-bed features are only available on selected aircraft and routes.</p>\n";
echo "                                    <img class=\"img-fluid d-block mx-auto\" src=\"assets/img/portfolio/meals2.jpg\" alt=\"...\" />\n";
echo "                                    <p>Whether you’re on a short or long haul flight, expect your meals to be served on Royal Doulton fine bone china along with cutlery exclusively made for you by Robert Welch.</p>\n";
echo "                                    <ul class=\"list-inline\">\n";
echo "                                        <li>\n";
echo "                                            <strong>Client:</strong>\n";
echo "                                            Business Class\n";
echo "                                        </li>\n";
echo "                                        <li>\n";
echo "                                            <strong>Category:</strong>\n";
echo "                                            Class and Meals\n";
echo "                                        </li>\n";
echo "                                        <li>\n";
echo "                                            <strong>Price</strong>\n";
echo "                                            MYR 900 (Per Pax)\n";
echo "                                        </li>\n";
echo "                                    </ul>\n";
echo "                                    <button class=\"btn btn-primary btn-xl text-uppercase\" data-bs-dismiss=\"modal\" type=\"button\">\n";
echo "                                        <i class=\"fas fa-times me-1\"></i>\n";
echo "                                        BACK TO FLIGHT PACKAGES\n";
echo "                                    </button>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "        <!-- Portfolio item 3 modal popup-->\n";
echo "        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal3\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n";
echo "            <div class=\"modal-dialog\">\n";
echo "                <div class=\"modal-content\">\n";
echo "                    <div class=\"close-modal\" data-bs-dismiss=\"modal\"><img src=\"assets/img/close-icon.svg\" alt=\"Close modal\" /></div>\n";
echo "                    <div class=\"container\">\n";
echo "                        <div class=\"row justify-content-center\">\n";
echo "                            <div class=\"col-lg-8\">\n";
echo "                                <div class=\"modal-body\">\n";
echo "                                    <!-- Project details-->\n";
echo "                                    <h2 class=\"text-uppercase\">Premium Economy</h2>\n";
echo "                                    <p class=\"item-intro text-muted\">• Premium Economy, slightly better Economy Class seating (greater distance between rows of seats; the seats themselves may or may not be wider than regular economy class).</p>\n";
echo "                                    <img class=\"img-fluid d-block mx-auto\" src=\"assets/img/portfolio/3.jpg\" alt=\"...\" />\n";
echo "                                    <p>In an exclusive, spacious cabin, our Premium Economy Class seats are designed with greater width for your enhanced comfort. Add that to the extra choices and exclusive privileges, brought together by the award-winning service you love, all you have left to do is sit back, relax, and smile.</p>\n";
echo "                                    <img class=\"img-fluid d-block mx-auto\" src=\"assets/img/portfolio/meals3.jpg\" alt=\"...\" />\n";
echo "                                    <p>Bon appétit’, ‘buon appetito’, enjoy your meal! For your first meal with us on board we serve you authentic classics from the cuisines of Central Europe. Look forward to dishes carefully prepared to the original recipe.</p>\n";
echo "                                    <ul class=\"list-inline\">\n";
echo "                                        <li>\n";
echo "                                            <strong>Client:</strong>\n";
echo "                                            Business Class\n";
echo "                                        </li>\n";
echo "                                        <li>\n";
echo "                                            <strong>Category:</strong>\n";
echo "                                            Class and Meals\n";
echo "                                        </li>\n";
echo "                                        <li>\n";
echo "                                            <strong>Price</strong>\n";
echo "                                            MYR 700 (Per Pax)\n";
echo "                                        </li>\n";
echo "                                    </ul>\n";
echo "                                    <button class=\"btn btn-primary btn-xl text-uppercase\" data-bs-dismiss=\"modal\" type=\"button\">\n";
echo "                                        <i class=\"fas fa-times me-1\"></i>\n";
echo "                                        BACK TO FLIGHT PACKAGES\n";
echo "                                    </button>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "        <!-- Portfolio item 4 modal popup-->\n";
echo "        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal4\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n";
echo "            <div class=\"modal-dialog\">\n";
echo "                <div class=\"modal-content\">\n";
echo "                    <div class=\"close-modal\" data-bs-dismiss=\"modal\"><img src=\"assets/img/close-icon.svg\" alt=\"Close modal\" /></div>\n";
echo "                    <div class=\"container\">\n";
echo "                        <div class=\"row justify-content-center\">\n";
echo "                            <div class=\"col-lg-8\">\n";
echo "                                <div class=\"modal-body\">\n";
echo "                                    <!-- Project details-->\n";
echo "                                    <h2 class=\"text-uppercase\">Economy Class</h2>\n";
echo "                                    <p class=\"item-intro text-muted\"> Economy Class (also known as coach class or travel class), basic accommodation, commonly purchased by leisure travelers.</p>\n";
echo "                                    <img class=\"img-fluid d-block mx-auto\" src=\"assets/img/portfolio/4.jpg\" alt=\"...\" />\n";
echo "                                    <p>You can travel a lot cheaper through economy classes. You can purchase cheap flights for both international and domestic flights. Except for some airline companies, almost all airlines have economy class. Airlines trying to provide much cheaper flight tickets for passengers are referred to as low-cost airlines. Pegasus offers many privileges for its passengers as a low-cost airline company. </p>\n";
echo "                                    <img class=\"img-fluid d-block mx-auto\" src=\"assets/img/portfolio/meals4.jpg\" alt=\"...\" />\n";
echo "                                    <p>Feast on a delectable paneer makhani. Bite into succulent chicken dipped in a sundried tomato pesto sauce. Our chefs are always learning about regional cuisines and techniques to offer you the world’s best flavours on board.</p>\n";
echo "                                    <ul class=\"list-inline\">\n";
echo "                                        <li>\n";
echo "                                            <strong>Client:</strong>\n";
echo "                                            Economy Class\n";
echo "                                        </li>\n";
echo "                                        <li>\n";
echo "                                            <strong>Category:</strong>\n";
echo "                                            Class and Meals\n";
echo "                                        </li>\n";
echo "                                        <li>\n";
echo "                                            <strong>Price</strong>\n";
echo "                                            MYR 500 (Per Pax)\n";
echo "                                        </li>\n";
echo "                                    </ul>\n";
echo "                                    <button class=\"btn btn-primary btn-xl text-uppercase\" data-bs-dismiss=\"modal\" type=\"button\">\n";
echo "                                        <i class=\"fas fa-times me-1\"></i>\n";
echo "                                        BACK TO FLIGHT PACKAGES\n";
echo "                                    </button>\n";
echo "                                </div>\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "       \n";
echo "            </div>\n";
echo "        </div>\n";
echo "        <!-- Bootstrap core JS-->\n";
echo "        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js\"></script>\n";
echo "        <!-- Core theme JS-->\n";
echo "        <script src=\"js/scripts.js\"></script>\n";
echo "        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\n";
echo "        <!-- * *                               SB Forms JS                               * *-->\n";
echo "        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->\n";
echo "        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->\n";
echo "        <script src=\"https://cdn.startbootstrap.com/sb-forms-latest.js\"></script>\n";

?>

</body>
</html>